### ISSUE TITLE
Exception when importing private key

### ISSUE THREAD

**Issue by rex4539** [vaklinov/zcash-swing-wallet-ui#39]
git @ f38d9fd

Steps:
Wallet -> Import one private key -> Paste the private key -> Click on "Import"

What happened:
The key is actually imported but an exception is thrown right when the import ends.

`
[Thread-850] [Sun Dec 24 23:21:55 EET 2017] [ERROR] An error occurred when importing private key 
com.vaklinov.zcashui.ZCashClientCaller$WalletCallException: Unexpected response from wallet: t1YX51Ra6Xi5BMxbt9sazML2d6uToCtwHXs

	at com.vaklinov.zcashui.ZCashClientCaller.importPrivateKey(ZCashClientCaller.java:863)
	at com.vaklinov.zcashui.SingleKeyImportDialog$3.run(SingleKeyImportDialog.java:201)
	at java.base/java.lang.Thread.run(Thread.java:844)
`

![screen shot 2017-12-24 at 23 22 22](https://user-images.githubusercontent.com/227442/34329260-a9d613fc-e901-11e7-9341-8bd83be8aa4e.png)
[ZCashGUIWallet_2017_12_debug.log](https://github.com/vaklinov/zcash-swing-wallet-ui/files/1585059/ZCashGUIWallet_2017_12_debug.log)

Expected result:
No exception.

**Comment by ronydj** [comment]
I am having the same issue... I got a key from jaxx.

I am not able to transfer from jaxx nor importing it to zcash4win

**Comment by serejandmyself** [comment]
Same issue

**Comment by DragonMagik** [comment]
I get the same exception importing a private key (originally generated by zcash4win when I first installed it) into a new instance.  Other addresses import fine, just this one does not.  After it throws the error it does show the correct balance.  However, I get a similar exception whenever I try to transfer money out of that address.  I haven't tried transferring zcash from a different address, but I can import other addresses without error.
